// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzGMiMbYxkuWXklv0PWg_SBMCzUaDX_4o',
    appId: '1:321167999466:web:8c629e15e1b207650d7293',
    messagingSenderId: '321167999466',
    projectId: 'voice-klip-1587f',
    authDomain: 'voice-klip-1587f.firebaseapp.com',
    databaseURL:
        'https://voice-klip-1587f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-klip-1587f.appspot.com',
    measurementId: 'G-JN2ZDCDG9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3b8EuM7304VTDdHM0taRBzFz_w4HRqGM',
    appId: '1:321167999466:android:80f1242663ce61680d7293',
    messagingSenderId: '321167999466',
    projectId: 'voice-klip-1587f',
    databaseURL:
        'https://voice-klip-1587f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-klip-1587f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYKdLIWeaOzTL-c6yu9B1rYbfmig17Bv0',
    appId: '1:321167999466:ios:b891ca24cfa8b1b20d7293',
    messagingSenderId: '321167999466',
    projectId: 'voice-klip-1587f',
    databaseURL:
        'https://voice-klip-1587f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-klip-1587f.appspot.com',
    iosBundleId: 'com.example.voiceklipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYKdLIWeaOzTL-c6yu9B1rYbfmig17Bv0',
    appId: '1:321167999466:ios:5d473906ed51decc0d7293',
    messagingSenderId: '321167999466',
    projectId: 'voice-klip-1587f',
    databaseURL:
        'https://voice-klip-1587f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-klip-1587f.appspot.com',
    iosBundleId: 'com.example.voiceklipApp.RunnerTests',
  );
}
